import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "NetArt Assessment",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`inter.className bg-gradient-to-t from-[#FFE5AD] to-[#F5F5DC]`}>{children}</body>
    </html>
  );
}
